#!/usr/bin/env python3
"""make-setup.py - embed the (human-readable) installers into the viewer.

The scripts are plain, short and readable on purpose: users can inspect them
in the page before running them, and they fetch their actual code from the
public repo, so what runs is what is published.

Reads  setup.bat, run-once.bat, uninstall.bat, setup-mac.command
Writes index.html (SETUP_FILES block: powers the download + "read before
       running" links)

    python tools/make-setup.py
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FILES = {
    'run':       'run-once.bat',
    'win':       'setup.bat',
    'uninstall': 'uninstall.bat',
    'mac':       'setup-mac.command',
}

payload = {}
for key, name in FILES.items():
    p = ROOT / name
    if not p.exists():
        sys.exit('ERROR: missing ' + name)
    text = p.read_text(encoding='utf-8')
    if name.endswith('.bat'):                      # cmd.exe needs CRLF
        text = text.replace('\r\n', '\n').replace('\n', '\r\n')
        p.write_bytes(text.encode('ascii'))
    payload[key] = {'name': name, 'content': text}
    if '</script' in text.lower():
        sys.exit('ERROR: %s would break the embedding' % name)

html_path = ROOT / 'index.html'
html = html_path.read_text(encoding='utf-8')
block = ('  // __SETUP_FILES_START__ (generated by tools/make-setup.py - do not edit)\n'
         '  const SETUP_FILES = ' + json.dumps(payload, ensure_ascii=True) + ';\n'
         '  // __SETUP_FILES_END__')
new_html, n = re.subn(r'  // __SETUP_FILES_START__[\s\S]*?// __SETUP_FILES_END__',
                      lambda m: block, html, count=1)
if n != 1:
    sys.exit('ERROR: SETUP_FILES markers not found in index.html')
html_path.write_text(new_html, encoding='utf-8', newline='\n')

print('embedded: ' + ', '.join('%s (%d B)' % (v['name'], len(v['content']))
                               for v in payload.values()))
