#!/usr/bin/env python3
"""make-setup.py - single source of truth for the setup installers.

Reads  tools/serve-service.ps1.tpl and index.html
Writes setup.bat         (self-contained: embeds the service AND the viewer)
       setup-mac.command (self-contained bash + LaunchAgent, beta)
       index.html        (patches the SETUP_FILES block so the hosted viewer
                          can offer both installers as downloads)

setup.bat installs a loopback-only service that serves the viewer and reads the
Claude session store directly, then opens the browser - so the user's entire
onboarding is "double-click the file".

Run from the repo root after editing the template or the viewer:
    python tools/make-setup.py
"""
import base64, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORT = 7817
BAT_CHUNK = 3000          # base64 chars per echo line (cmd's limit is 8191)

html_path = ROOT / 'index.html'
html = html_path.read_text(encoding='utf-8')

# The embedded viewer must not carry a stale SETUP_FILES payload (that would
# nest installer inside installer), so blank it before embedding.
html_for_service = re.sub(
    r'  // __SETUP_FILES_START__[\s\S]*?// __SETUP_FILES_END__',
    '  // __SETUP_FILES_START__ (stripped in the local build)\n'
    '  const SETUP_FILES = {};\n  // __SETUP_FILES_END__',
    html, count=1)

ps1 = (ROOT / 'tools' / 'serve-service.ps1.tpl').read_text(encoding='utf-8')
ps1 = ps1.replace('{PORT}', str(PORT)).replace(
    '{HTML_B64}', base64.b64encode(html_for_service.encode('utf-8')).decode('ascii'))

vbs = (
    "' run-hidden.vbs - starts the claudetldr service with no visible window.\r\n"
    'Dim fso, shell, dir\r\n'
    'Set fso = CreateObject("Scripting.FileSystemObject")\r\n'
    'Set shell = CreateObject("WScript.Shell")\r\n'
    'dir = fso.GetParentFolderName(WScript.ScriptFullName)\r\n'
    'shell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File """ '
    '& dir & "\\serve-service.ps1""", 0, False\r\n')

def b64_crlf(text):
    raw = text.replace('\r\n', '\n').replace('\n', '\r\n')
    return base64.b64encode(raw.encode('utf-8')).decode('ascii')

def echo_chunks(b64, var):
    """cmd lines are capped at 8191 chars, so write the payload in pieces."""
    lines = []
    for i in range(0, len(b64), BAT_CHUNK):
        lines.append('echo %s>>"%%TMP%%\\%s"' % (b64[i:i + BAT_CHUNK], var))
    return '\n'.join(lines)

ps1_b64 = b64_crlf(ps1)
vbs_b64 = b64_crlf(vbs)

BAT = r"""@echo off
setlocal
REM claudetldr setup (Windows) - self-contained, no admin rights needed.
REM Installs a loopback-only service that serves the viewer at
REM http://127.0.0.1:{PORT} and reads your Claude conversations directly.
REM Nothing is copied anywhere, nothing leaves the machine.
REM Generated by tools/make-setup.py - do not edit by hand.
REM Undo: uninstall.bat, or delete the 'claudetldr' entry under
REM HKCU\Software\Microsoft\Windows\CurrentVersion\Run plus %LOCALAPPDATA%\claudetldr.

set "INSTALL=%LOCALAPPDATA%\claudetldr"
mkdir "%INSTALL%" 2>nul

echo Installing claudetldr...

REM stop any previous instance so the upgrade replaces its files cleanly
powershell -NoProfile -Command "Get-CimInstance Win32_Process -Filter \"Name='powershell.exe'\" | Where-Object { $_.CommandLine -like '*serve-service.ps1*' -or $_.CommandLine -like '*sync-service.ps1*' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }" >nul 2>nul

del "%TMP%\cltl_ps1.b64" 2>nul
del "%TMP%\cltl_vbs.b64" 2>nul
{PS1_CHUNKS}
{VBS_CHUNKS}

powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%INSTALL%\serve-service.ps1',[Convert]::FromBase64String(((Get-Content -Raw '%TMP%\cltl_ps1.b64') -replace '\s','')))" || goto :err
powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%INSTALL%\run-hidden.vbs',[Convert]::FromBase64String(((Get-Content -Raw '%TMP%\cltl_vbs.b64') -replace '\s','')))" || goto :err
del "%TMP%\cltl_ps1.b64" 2>nul
del "%TMP%\cltl_vbs.b64" 2>nul

REM autostart at logon (per-user key: no admin needed), then start it now
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "claudetldr" /t REG_SZ /d "wscript.exe \"%INSTALL%\run-hidden.vbs\"" /f >nul || goto :err
REM drop the pre-v16 mirror autostart if this is an upgrade
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "claudetldr-sync" /f >nul 2>nul
start "" wscript.exe "%INSTALL%\run-hidden.vbs"

REM give the service a moment, then open the viewer
powershell -NoProfile -Command "Start-Sleep -Milliseconds 1500" >nul
start "" "http://127.0.0.1:{PORT}/"

echo.
echo   Done - your conversations should be opening in the browser now.
echo   Bookmark http://127.0.0.1:{PORT}/  (starts by itself after every logon)
echo.
pause
exit /b 0

:err
echo.
echo   Setup failed. Run this as your normal user (no admin needed).
pause
exit /b 1
"""

bat = (BAT.replace('{PS1_CHUNKS}', echo_chunks(ps1_b64, 'cltl_ps1.b64'))
          .replace('{VBS_CHUNKS}', echo_chunks(vbs_b64, 'cltl_vbs.b64'))
          .replace('{PORT}', str(PORT)))
bat_bytes = bat.replace('\r\n', '\n').replace('\n', '\r\n').encode('ascii')
(ROOT / 'setup.bat').write_bytes(bat_bytes)

# --------------------------------------------------------- setup-mac.command
MAC_TPL = r"""#!/bin/bash
# claudetldr setup (macOS, beta) - installs a loopback-only service that serves
# the viewer at http://127.0.0.1:{PORT} and reads your Claude conversations
# directly. Nothing is copied anywhere, nothing leaves the machine.
# Downloaded files lose the execute bit, so run it with:
#     bash ~/Downloads/setup-mac.command
# Undo:  launchctl unload ~/Library/LaunchAgents/com.claudetldr.plist
#        rm ~/Library/LaunchAgents/com.claudetldr.plist
#        rm -rf "$HOME/Library/Application Support/claudetldr"
set -e
INSTALL="$HOME/Library/Application Support/claudetldr"
mkdir -p "$INSTALL"
python3 - <<'PYEOF' > "$INSTALL/index.html"
import base64
print(base64.b64decode("{HTML_B64}").decode("utf-8"), end="")
PYEOF

cat > "$INSTALL/serve.py" <<'PYSRV'
import http.server, json, os, socketserver, urllib.parse
PORT = {PORT}
STORE = os.path.expanduser("~/Library/Application Support/Claude/local-agent-mode-sessions")
HERE = os.path.dirname(os.path.abspath(__file__))
SKIP = {"outputs", "uploads", "node_modules", ".git", ".claude"}

def sessions():
    out = []
    def walk(d, depth):
        if depth > 8:
            return
        try:
            entries = list(os.scandir(d))
        except OSError:
            return
        for e in entries:
            if not e.is_dir() or e.name in SKIP:
                continue
            audit = os.path.join(e.path, "audit.jsonl")
            if os.path.isfile(audit):
                title = None
                meta = os.path.join(d, e.name + ".json")
                if os.path.isfile(meta):
                    try:
                        with open(meta, encoding="utf-8") as f:
                            title = (json.load(f) or {}).get("title")
                    except Exception:
                        title = None
                st = os.stat(audit)
                out.append({"id": os.path.relpath(audit, STORE), "title": title,
                            "mtime": int(st.st_mtime * 1000), "size": st.st_size})
            else:
                walk(e.path, depth + 1)
    if os.path.isdir(STORE):
        walk(STORE, 0)
    out.sort(key=lambda s: s["mtime"], reverse=True)
    return out

class H(http.server.BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _send(self, code, ctype, body, extra=None):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        parts = urllib.parse.urlparse(self.path)
        if parts.path in ("/", "/index.html"):
            with open(os.path.join(HERE, "index.html"), "rb") as f:
                self._send(200, "text/html; charset=utf-8", f.read())
        elif parts.path == "/api/sessions":
            self._send(200, "application/json; charset=utf-8",
                       json.dumps(sessions()).encode("utf-8"))
        elif parts.path == "/api/audit":
            sid = urllib.parse.parse_qs(parts.query).get("id", [""])[0]
            full = os.path.realpath(os.path.join(STORE, sid))
            if (full.startswith(os.path.realpath(STORE) + os.sep)
                    and os.path.basename(full) == "audit.jsonl" and os.path.isfile(full)):
                with open(full, "rb") as f:
                    data = f.read()
                self._send(200, "text/plain; charset=utf-8", data,
                           {"X-Mtime": str(int(os.stat(full).st_mtime * 1000))})
            else:
                self._send(404, "text/plain", b"not found")
        else:
            self._send(404, "text/plain", b"not found")

class S(socketserver.ThreadingTCPServer):
    allow_reuse_address = True

S(("127.0.0.1", PORT), H).serve_forever()
PYSRV

PLIST="$HOME/Library/LaunchAgents/com.claudetldr.plist"
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.claudetldr</string>
  <key>ProgramArguments</key><array>
    <string>/usr/bin/python3</string><string>$INSTALL/serve.py</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
PLIST_EOF
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
sleep 2
open "http://127.0.0.1:{PORT}/"
echo "claudetldr installed - the viewer should be opening at http://127.0.0.1:{PORT}/"
"""
mac = (MAC_TPL.replace('{PORT}', str(PORT))
              .replace('{HTML_B64}', base64.b64encode(html_for_service.encode('utf-8')).decode('ascii')))
(ROOT / 'setup-mac.command').write_text(mac, encoding='utf-8', newline='\n')

# ------------------------------------------------------------- index.html
block = ('  // __SETUP_FILES_START__ (generated by tools/make-setup.py - do not edit)\n'
         '  const SETUP_FILES = ' + json.dumps({
             'win': {'name': 'setup.bat', 'content': bat_bytes.decode('ascii')},
             'mac': {'name': 'setup-mac.command', 'content': mac},
         }, ensure_ascii=True) + ';\n'
         '  // __SETUP_FILES_END__')
new_html, n = re.subn(
    r'  // __SETUP_FILES_START__[\s\S]*?// __SETUP_FILES_END__',
    lambda m: block, html, count=1)
if n != 1:
    sys.exit('ERROR: SETUP_FILES markers not found in index.html')
html_path.write_text(new_html, encoding='utf-8', newline='\n')

print('wrote setup.bat (%d bytes, longest line %d), setup-mac.command (%d bytes), patched index.html'
      % (len(bat_bytes), max(len(l) for l in bat_bytes.decode().split('\r\n')), len(mac)))
