#!/usr/bin/env python3
"""make-setup.py - single source of truth for the setup installers.

Reads  tools/sync-service.ps1 and tools/run-hidden.vbs
Writes setup.bat (self-contained: embeds both files as base64)
       setup-mac.command (self-contained bash + LaunchAgent)
       index.html (patches the SETUP_FILES block between markers so the
                   hosted viewer can offer both installers as downloads)

Run from the repo root after editing any of the source files:
    python tools/make-setup.py
"""
import base64, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

ps1 = (ROOT / 'tools' / 'sync-service.ps1').read_text(encoding='utf-8')
vbs = (ROOT / 'tools' / 'run-hidden.vbs').read_text(encoding='utf-8')

def b64(text, crlf):
    raw = text.replace('\r\n', '\n')
    if crlf:
        raw = raw.replace('\n', '\r\n')
    return base64.b64encode(raw.encode('utf-8')).decode('ascii')

# ---------------------------------------------------------------- setup.bat
BAT = r"""@echo off
setlocal
REM claudetldr setup (Windows) - self-contained, no admin rights needed.
REM Installs an invisible sync that mirrors your Claude conversations to
REM Downloads\claude-sessions so the viewer can connect once and reconnect
REM automatically forever after. Generated by tools/make-setup.py.
REM Undo anytime: delete the 'claudetldr-sync' entry under
REM HKCU\Software\Microsoft\Windows\CurrentVersion\Run and the folder
REM %LOCALAPPDATA%\claudetldr (or run uninstall.bat from the repo).

set "INSTALL=%LOCALAPPDATA%\claudetldr"
mkdir "%INSTALL%" 2>nul

REM stop a running sync instance so upgrades replace the script cleanly
powershell -NoProfile -Command "Get-CimInstance Win32_Process -Filter \"Name='powershell.exe'\" | Where-Object { $_.CommandLine -like '*sync-service.ps1*' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }" >nul 2>nul

powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%INSTALL%\sync-service.ps1',[Convert]::FromBase64String('{PS1_B64}'))" || goto :err
powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%INSTALL%\run-hidden.vbs',[Convert]::FromBase64String('{VBS_B64}'))" || goto :err

reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "claudetldr-sync" /t REG_SZ /d "wscript.exe \"%INSTALL%\run-hidden.vbs\"" /f || goto :err
start "" wscript.exe "%INSTALL%\run-hidden.vbs"

echo.
echo   claudetldr sync installed and running (invisible).
echo.
echo   mirrors  %%APPDATA%%\Claude\local-agent-mode-sessions
echo   to       %%USERPROFILE%%\Downloads\claude-sessions   (every ~2 seconds)
echo.
echo   Last step, once: open the viewer, click "connect Cowork" and pick
echo   Downloads\claude-sessions. It reconnects by itself from then on.
echo.
pause
exit /b 0

:err
echo Setup failed - run this as your normal user (no admin needed).
pause
exit /b 1
"""

bat = BAT.replace('{PS1_B64}', b64(ps1, crlf=True)).replace('{VBS_B64}', b64(vbs, crlf=True))
bat_bytes = bat.replace('\r\n', '\n').replace('\n', '\r\n').encode('ascii')
(ROOT / 'setup.bat').write_bytes(bat_bytes)

# --------------------------------------------------------- setup-mac.command
MAC = r"""#!/bin/bash
# claudetldr setup (macOS, beta) - installs an invisible sync that mirrors
# your Claude conversations to ~/Downloads/claude-sessions.
# Downloaded files lose the execute bit, so run it with:
#     bash ~/Downloads/setup-mac.command
# Undo:  launchctl unload ~/Library/LaunchAgents/com.claudetldr.sync.plist
#        rm ~/Library/LaunchAgents/com.claudetldr.sync.plist
#        rm -rf "$HOME/Library/Application Support/claudetldr"
set -e
INSTALL="$HOME/Library/Application Support/claudetldr"
mkdir -p "$INSTALL"

cat > "$INSTALL/sync.sh" <<'SYNC'
#!/bin/bash
SRC="$HOME/Library/Application Support/Claude/local-agent-mode-sessions"
DST="$HOME/Downloads/claude-sessions"
while true; do
  if [ -d "$SRC" ]; then
    find "$SRC" -name audit.jsonl -print0 2>/dev/null | while IFS= read -r -d '' f; do
      rel="${f#$SRC/}"; out="$DST/$rel"
      if [ ! -f "$out" ] || [ "$f" -nt "$out" ]; then
        mkdir -p "$(dirname "$out")" && cp -p "$f" "$out" 2>/dev/null
      fi
    done
  fi
  sleep 2
done
SYNC
chmod +x "$INSTALL/sync.sh"

PLIST="$HOME/Library/LaunchAgents/com.claudetldr.sync.plist"
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.claudetldr.sync</string>
  <key>ProgramArguments</key><array><string>$INSTALL/sync.sh</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
PLIST_EOF
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "claudetldr sync installed (invisible)."
echo "Now open the viewer, click 'connect Cowork' and pick Downloads/claude-sessions once."
"""
(ROOT / 'setup-mac.command').write_text(MAC, encoding='utf-8', newline='\n')

# ------------------------------------------------------------- index.html
html_path = ROOT / 'index.html'
html = html_path.read_text(encoding='utf-8')
block = ('  // __SETUP_FILES_START__ (generated by tools/make-setup.py - do not edit)\n'
         '  const SETUP_FILES = ' + json.dumps({
             'win': {'name': 'setup.bat', 'content': bat_bytes.decode('ascii')},
             'mac': {'name': 'setup-mac.command', 'content': MAC},
         }, ensure_ascii=True) + ';\n'
         '  // __SETUP_FILES_END__')
new_html, n = re.subn(
    r'  // __SETUP_FILES_START__[\s\S]*?// __SETUP_FILES_END__',
    lambda m: block, html, count=1)
if n != 1:
    sys.exit('ERROR: SETUP_FILES markers not found in index.html')
html_path.write_text(new_html, encoding='utf-8', newline='\n')

print('wrote setup.bat (%d bytes), setup-mac.command (%d bytes), patched index.html'
      % (len(bat_bytes), len(MAC)))
